# CS 383 HW #2 - PlantUML Makefile

CLASS = compiler-classidagram
CASE = compiler-use-case
CC = java -jar plantuml.jar
FLAGS = -tpng

all: 
	${CC} ${FLAGS} *.uml

${CLASS}.uml: 
	${CC} ${FLAGS} ${FILE}.uml
	
${CASE}.uml: 
	${CC} ${FLAGS} ${FILE}.uml

clean:
	rm -f ${FILE}.latex